dist: xenial
language: java
jdk:
- openjdk8
- openjdk11
deploy:
- provider: s3
  access_key_id: AKIAISBC3VLMF6YLNJTA
  secret_access_key: &1
    secure: Yasg3HXB04LzMOL8xIpRpKeJG/F9w6yk3KMyetmunRtbaW7iY2I6OPZqrEKnBr3EQPGnO12UNWpZKytLeqrbtxltvDAUJLA4KlKeKYuLePMulnbp85ZCjI8JBpFSRq1y6krFLIhX6JXWsYCQVx22tXYTZnHqYuFalMBlf/ps/TnsSbT/3QB+eJXRTWnfDwpfcydOf1lJOcj5ndoqEibc34tDiespnzBcQcGf7hS9gUH4zfXMGAaZwu1uNA1z3ObIplZbTxnSDC1IIKanU6Zf51pR4qrlg5jaUNAi1VQqR7IyGlJ/AYkMsGgPJqKWxdijVsnC3GEc7sAQaSvLzzsmFXV2Qv3cHlI5Nosyit2x3g/cSkayZyh9qAJtDhnhOmSyw2YaBwWIGRGK6d2gJKa+RSP8YNaUiO3swo3AxWzapliv+AhotyjYlBs7jSzKcbZtI0mHfceCu3nvI21PBwqw8t9aWk5wL6szNBTMNAuq5eRM7HpvYM/NSB58Q7HwQzmBM2H06aAomq1KMUlR6lBhID/a9djSh3fgYGSHIeYLlzFPQiBDKXxbW5cG+qkjbP1aLX+mRdeaDa5XvSPJw9l3TIERo8iJu526cvSqguHSeH3E9pvE4TviGMAlAo3ik1W6qSBu1BpEcR0UeyHeRMHppWSOe37bn1q5lbtKJNJzAjI=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: Akus/travis-ci-tutorial-java
  bucket: elasticbeanstalk-eu-central-1-823514127427
- provider: codedeploy
  access_key_id: AKIAISBC3VLMF6YLNJTA
  secret_access_key: *1
  bucket: elasticbeanstalk-eu-central-1-823514127427
  key: latest.zip
  bundle_type: zip
  application: travis-ci-tutorial-java
  deployment_group: ProductionDemoFleet
  on: *2
  skip_cleanup: 'true'
before_deploy:
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
